
local generator0 = util.table.deepcopy(data.raw["container"]["wooden-chest"])
generator0.name = "cursed-generator"
generator0.flags = {}
generator0.minable.mining_time = 2
generator0.minable.result = "cursed-generator-0"
generator0.max_health = 750
generator0.corpse = "medium-remnants"
generator0.collision_box = {{-3.25, -3.25}, {3.25, 3.25}}
generator0.selection_box = {{-3.5, -3.5}, {3.5, 3.5}}
generator0.inventory_size = 1
generator0.open_sound.filename = "__base__/sound/machine-open.ogg"
generator0.open_sound.volume = 0.85
generator0.close_sound.filename = "__base__/sound/machine-close.ogg"
generator0.close_sound.volume = 0.75
generator0.picture.filename = "__Cursed-Exp__/graphics/entities/invi.png"
generator0.picture.width = 1
generator0.picture.height = 1
generator0.picture.shift = {0, 0}
data.raw[generator0.type][generator0.name] = generator0

for i = 0, datos.maxgenerator + 1 do
	local generator = util.table.deepcopy(data.raw["accumulator"]["basic-accumulator"])
	generator.name = "cursed-generator-" .. i
	generator.icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png"
	generator.corpse = "big-remnants"
	generator.collision_box = {{-3.25, -3.25}, {3.25, 3.25}}
	generator.selection_box = nil
	generator.energy_source.usage_priority = "primary-output"
	local output_flow_limit = math.floor((0.1 * (i - 1)^2 + (i - 1) * 25) * 1.5 + 25)
	if  i == datos.maxgenerator + 1 then
		output_flow_limit = math.floor((0.25 * (i - 1)^2 + (i - 1) * 25) * 1.5 + 25)
	end
	generator.energy_source.output_flow_limit = output_flow_limit .. "kW"
	generator.energy_source.buffer_capacity = output_flow_limit * 60 * 5 .. "kW"
	local f = math.ceil(i * datos.maxgeneratorimg / datos.maxgenerator)
	if f < 10 then
		generator.picture.filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-0" .. f ..".png"
	else
		generator.picture.filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-" .. f ..".png"
	end
	generator.picture.width = 288
	generator.picture.height = 288
	generator.picture.shift = {0.53,0.15}
	generator.picture.scale = 0.9
	generator.charge_cooldown = 30
	generator.charge_animation = nil
	generator.discharge_cooldown = 120
	generator.discharge_animation = nil
	generator.discharge_light.intensity = 1
	generator.discharge_light.size = 15
	generator.order = "c-f"
	data.raw[generator.type][generator.name] = generator
end

-- data:extend(
-- {

  -- {
    -- type = "container",
    -- name = "cursed-generator",
    -- icon = "__base__/graphics/icons/wooden-chest.png",
    -- flags = {},
    -- minable = {hardness = 1, mining_time = 2, result = "cursed-generator-0"},
    -- max_health = 750,
    -- corpse = "small-remnants",
    -- fast_replaceable_group = "container",
	-- collision_box = {{-3.25, -3.25}, {3.25, 3.25}},	--
	-- selection_box = {{-3.5, -3.5}, {3.5, 3.5}},	--
    -- inventory_size = 1,
    -- open_sound = { filename = "__base__/sound/wooden-chest-open.ogg" },
    -- close_sound = { filename = "__base__/sound/wooden-chest-close.ogg" },
    -- picture =
    -- {
		-- filename = "__Cursed-Exp__/graphics/entities/invi.png",
		-- priority = "extra-high",
		-- width = 1,
		-- height = 1,
		-- shift = {0, 0}
    -- }
  -- },

-- { type = "accumulator", name = "cursed-generator-0", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "1250kJ", usage_priority = "primary-output", output_flow_limit = "25kW"}, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-00.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-1", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "1250kJ", usage_priority = "primary-output", output_flow_limit = "25kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-01.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-2", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "2500kJ", usage_priority = "primary-output", output_flow_limit = "50kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-02.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-3", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "3750kJ", usage_priority = "primary-output", output_flow_limit = "75kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-03.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-4", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "5000kJ", usage_priority = "primary-output", output_flow_limit = "100kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-04.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-5", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "6300kJ", usage_priority = "primary-output", output_flow_limit = "126kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-05.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-6", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "7600kJ", usage_priority = "primary-output", output_flow_limit = "152kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-06.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-7", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "8900kJ", usage_priority = "primary-output", output_flow_limit = "178kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-07.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-8", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "10200kJ", usage_priority = "primary-output", output_flow_limit = "204kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-08.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-9", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "11550kJ", usage_priority = "primary-output", output_flow_limit = "231kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-09.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-10", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "12900kJ", usage_priority = "primary-output", output_flow_limit = "258kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-10.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-11", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "14250kJ", usage_priority = "primary-output", output_flow_limit = "285kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-11.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-12", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "15600kJ", usage_priority = "primary-output", output_flow_limit = "312kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-12.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-13", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "16950kJ", usage_priority = "primary-output", output_flow_limit = "339kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-13.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-14", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "18300kJ", usage_priority = "primary-output", output_flow_limit = "366kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-14.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-15", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "19700kJ", usage_priority = "primary-output", output_flow_limit = "394kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-15.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-16", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "21100kJ", usage_priority = "primary-output", output_flow_limit = "422kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-16.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-17", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "22500kJ", usage_priority = "primary-output", output_flow_limit = "450kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-17.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-18", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "23900kJ", usage_priority = "primary-output", output_flow_limit = "478kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-18.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-19", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "25350kJ", usage_priority = "primary-output", output_flow_limit = "507kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-19.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-20", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "26800kJ", usage_priority = "primary-output", output_flow_limit = "536kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-20.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-21", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "28250kJ", usage_priority = "primary-output", output_flow_limit = "565kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-21.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-22", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "29700kJ", usage_priority = "primary-output", output_flow_limit = "594kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-22.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-23", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "31150kJ", usage_priority = "primary-output", output_flow_limit = "623kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-23.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-24", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "32600kJ", usage_priority = "primary-output", output_flow_limit = "652kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-24.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-25", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "34100kJ", usage_priority = "primary-output", output_flow_limit = "682kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-25.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-26", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "35600kJ", usage_priority = "primary-output", output_flow_limit = "712kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-26.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-27", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "37100kJ", usage_priority = "primary-output", output_flow_limit = "742kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-27.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-28", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "38600kJ", usage_priority = "primary-output", output_flow_limit = "772kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-28.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-29", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "40150kJ", usage_priority = "primary-output", output_flow_limit = "803kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-29.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-30", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "41700kJ", usage_priority = "primary-output", output_flow_limit = "834kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-30.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-31", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "43250kJ", usage_priority = "primary-output", output_flow_limit = "865kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-31.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-32", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "44800kJ", usage_priority = "primary-output", output_flow_limit = "896kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-32.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-33", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "46350kJ", usage_priority = "primary-output", output_flow_limit = "927kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-33.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-34", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "47900kJ", usage_priority = "primary-output", output_flow_limit = "958kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-34.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-35", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "49500kJ", usage_priority = "primary-output", output_flow_limit = "990kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-35.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-36", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "51100kJ", usage_priority = "primary-output", output_flow_limit = "1022kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-36.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-37", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "52700kJ", usage_priority = "primary-output", output_flow_limit = "1054kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-37.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-38", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "54300kJ", usage_priority = "primary-output", output_flow_limit = "1086kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-38.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-39", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "55950kJ", usage_priority = "primary-output", output_flow_limit = "1119kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-39.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-40", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "57600kJ", usage_priority = "primary-output", output_flow_limit = "1152kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-40.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-41", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "59250kJ", usage_priority = "primary-output", output_flow_limit = "1185kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-41.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-42", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "60900kJ", usage_priority = "primary-output", output_flow_limit = "1218kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-42.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-43", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "62550kJ", usage_priority = "primary-output", output_flow_limit = "1251kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-43.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-44", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "64200kJ", usage_priority = "primary-output", output_flow_limit = "1284kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-44.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-45", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "65900kJ", usage_priority = "primary-output", output_flow_limit = "1318kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-45.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-46", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "67600kJ", usage_priority = "primary-output", output_flow_limit = "1352kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-46.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-47", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "69300kJ", usage_priority = "primary-output", output_flow_limit = "1386kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-47.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-48", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "71000kJ", usage_priority = "primary-output", output_flow_limit = "1420kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-48.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-49", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "72750kJ", usage_priority = "primary-output", output_flow_limit = "1455kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-49.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-50", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "74500kJ", usage_priority = "primary-output", output_flow_limit = "1490kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-50.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-51", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "76250kJ", usage_priority = "primary-output", output_flow_limit = "1525kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-51.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-52", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "78000kJ", usage_priority = "primary-output", output_flow_limit = "1560kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-52.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-53", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "79750kJ", usage_priority = "primary-output", output_flow_limit = "1595kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-53.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-54", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "81500kJ", usage_priority = "primary-output", output_flow_limit = "1630kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-54.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-55", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "83300kJ", usage_priority = "primary-output", output_flow_limit = "1666kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-55.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-56", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "85100kJ", usage_priority = "primary-output", output_flow_limit = "1702kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-56.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-57", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "86900kJ", usage_priority = "primary-output", output_flow_limit = "1738kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-57.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-58", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "88700kJ", usage_priority = "primary-output", output_flow_limit = "1774kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-58.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-59", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "90550kJ", usage_priority = "primary-output", output_flow_limit = "1811kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-59.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-60", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "92400kJ", usage_priority = "primary-output", output_flow_limit = "1848kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-60.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-61", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "94250kJ", usage_priority = "primary-output", output_flow_limit = "1885kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-61.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-62", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "96100kJ", usage_priority = "primary-output", output_flow_limit = "1922kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-62.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-63", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "97950kJ", usage_priority = "primary-output", output_flow_limit = "1959kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-63.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-64", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "99800kJ", usage_priority = "primary-output", output_flow_limit = "1996kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-64.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 
-- { type = "accumulator", name = "cursed-generator-65", icon = "__Cursed-Exp__/graphics/icons/generator/cursed-generator-00.png", flags = {"placeable-neutral", "player-creation"}, max_health = 150, corpse = "big-remnants", collision_box = {{-3.25, -3.25}, {3.25, 3.25}}, energy_source = { type = "electric", buffer_capacity = "122200kJ", usage_priority = "primary-output", output_flow_limit = "2444kW"}, charge_cooldown = 30, picture = { filename = "__Cursed-Exp__/graphics/entities/generator/cursed-generator-65.png", priority = "very-low", width = 288, height = 288, shift = {0.53,0.15}, scale = 0.9 }, charge_cooldown = 30, discharge_cooldown = 120, discharge_light = {intensity = 1, size = 15}, working_sound = { sound = { filename = "__base__/sound/accumulator-working.ogg", volume = 1 }, idle_sound = { filename = "__base__/sound/accumulator-idle.ogg", volume = 0.4 }, max_sounds_per_type = 1 }, order = "c-f", }, 

-- }
-- )