function sunken_sound()
return
	{
		{
			filename = "__base__/sound/creatures/worm-roar-short-1.ogg",
			volume = 0.4
		},
		{
			filename = "__base__/sound/creatures/worm-roar-short-2.ogg",
			volume = 0.4
		},
		{
			filename = "__base__/sound/creatures/worm-roar-short-3.ogg",
			volume = 0.4
		}
	}
end

function sunken_stand()
  return
  {
		layers=
		{
			{
				width = 96,
				height = 80,
				frame_count = 4,
				axially_symmetrical = false,
				direction_count = 1,
				shift = {-0.3, -0.4},
				scale = 1.25,
				animation_speed = 0.3,
				stripes =
				{
					{
						filename = "__Cursed-Exp__/graphics/entities/turret/cursed-turret-normal-1.png",
						width_in_frames = 4,
						height_in_frames = 1,
					}
				}
			}
		}
	}
end
function sunken_attack(run_mode)
	return
	{
		layers=
		{
			{
				width = 96,
				height = 80,
				frame_count = 10,
				axially_symmetrical = false,
				direction_count = 8,
				shift = {-0.3, -0.4},
				scale = 1.25,
				run_mode = run_mode,
				stripes =
				{
					{
						filename = "__Cursed-Exp__/graphics/entities/turret/cursed-turret-attack-1.png",
						width_in_frames = 10,
						height_in_frames = 8,
					}
				}
			}
		}
	}
end

data:extend({
	{ type = "explosion", name = "sunken_spike", flags = {"not-on-map"}, animations = { { filename = "__Cursed-Exp__/graphics/entities/turret/cursed-turret-spike-1.png", priority = "extra-high", width = 26, height = 36, frame_count = 12, animation_speed = 0.6, shift = {0, 0.5}, scale = 1.5 } }, },
	{ type = "turret", name = "cursed-turret-1", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 200, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 7.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 3 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-2", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 225, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 8, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 6 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-3", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 250, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 8.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 9 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-4", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 275, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 9, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 12 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-5", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 300, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 9.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 15 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-6", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 325, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 10, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 18 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-7", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 350, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 10.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 21 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-8", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 375, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 11, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 24 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-9", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 400, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 11.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 27 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-10", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 425, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 12, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 30 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-11", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 450, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 12.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 33 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-12", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 475, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 13, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 36 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-13", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 500, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 13.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 39 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-14", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 525, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 14, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 42 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-15", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 550, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 14.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 45 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-16", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 575, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 15, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 48 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-17", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 600, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 15.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 51 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-18", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 625, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 16, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 54 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-19", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 650, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 16.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 57 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-20", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 675, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 17, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 60 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-21", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 700, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 17.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 63 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-22", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 725, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 18, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 66 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-23", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 750, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 18.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 69 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-24", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 775, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 19, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 72 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-25", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 800, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 19.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 75 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-26", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 825, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 20, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 78 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-27", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 850, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 20.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 81 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-28", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 875, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 21, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 84 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-29", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 900, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 21.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 87 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-30", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 925, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 22, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 90 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-31", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 950, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 22.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 93 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-32", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 975, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 23, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 96 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-33", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1000, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 23.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 99 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-34", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1025, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 24, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 102 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-35", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1050, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 24.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 105 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-36", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1075, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 25, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 108 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-37", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1100, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 25.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 111 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-38", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1125, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 26, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 114 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-39", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1150, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 26.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 117 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-40", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1175, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 27, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 120 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-41", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1200, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 27.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 123 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-42", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1225, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 28, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 126 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-43", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1250, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 28.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 129 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-44", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1275, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 29, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 132 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-45", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1300, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 29.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 135 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-46", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1325, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 30, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 138 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-47", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1350, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 30.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 141 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-48", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1375, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 31, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 144 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-49", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1400, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 31.5, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 147 , type = "physical"} } } } } } } } } },
	{ type = "turret", name = "cursed-turret-50", icon = "__Cursed-Exp__/graphics/icons/turret/cursed-turret-1.jpg", flags = {"placeable-player", "not-repairable", "breaths-air"}, order="b-b-d", max_health = 1425, subgroup="cursed-build", collision_box = {{-1.4, -1.4}, {1.4, 1.4}}, selection_box = {{-1.5, -1.5}, {1.5, 1.5}}, shooting_cursor_size = 5, corpse = "small-worm-corpse", dying_explosion = "blood-explosion-big", minable = {mining_time = 5, result = "cursed-turret-1"}, folded_speed = 0.01, folded_animation = sunken_stand(), starting_attack_speed = 0.03, starting_attack_animation = sunken_attack("forward"), starting_attack_sound = sunken_sound(), ending_attack_speed = 0.03, ending_attack_animation = sunken_attack("backward"), attack_parameters = { ammo_category = "bullet", cooldown = 1, range = 32, ammo_type = { category = "bullet", action = { { type = "direct", action_delivery = { { type = "instant", target_effects = { { type = "create-entity", entity_name = "sunken_spike" }, { type = "damage", damage = { amount = 150 , type = "physical"} } } } } } } } } },

})
